import type { Metadata } from 'next'
import './globals.css'
import { ModalProvider } from '@/components/providers/modal-provider'

export const metadata: Metadata = {
  title: 'Baby Time Machine',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
      <ModalProvider />
    </html>
  )
}
